from typing import Protocol


class Target(Protocol):
    def expect(self, terminal: str, pattern: str, timeout: float | int) -> int: ...
    def sendline(self, terminal: str, line: bytes = b"") -> None: ...
    def before(self, terminal: str) -> bytes: ...


class Logger(Protocol):
    def debug(self, message: str, *args: str) -> None: ...
    def info(self, message: str, *args: str) -> None: ...


class SafetyIslandCLIUtils:
    def __init__(self, target: Target, console: str, logger: Logger) -> None: ...
    def run(self, cmd: str, timeout: int = 60) -> str: ...
    def get_status(self, cpu: int) -> str: ...
    def run_tests(self, cpu: int) -> str: ...
    def count(self, cpu: int) -> str: ...
    def count_block(self, cpu: int, blk_id: int) -> str: ...
    def result(self, cpu: int) -> str: ...
    def set_state(self, cpu: int, state: int) -> str: ...
    def force_error(self, cpu: int, err: int) -> str: ...
    def run_block(self, cpu: int, blk_id: int) -> str: ...
    def run_part_range(
        self,
        cpu: int,
        blk_id: int,
        start: int,
        end: int,
    ) -> str: ...
