class ScpCliUtils:
    TIMEOUT: int
    def enter_cli(self, target, console: str) -> None: ...
    def exit_cli(self, target, console: str) -> None: ...
    def wait_for_pattern(self, target, console: str, pattern: str) -> None: ...


class ScpTestUtils:
    TEST_RESULT_RE: str
    SUMMARY_RE: str
    console: str
    def run_test(self, test_name: str) -> None: ...
